apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo
spec:
  template:
    spec:
      containers:
      - name: myapp
        env:
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: ai
              key: connectionstring
