apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo
spec:
  template:
    spec:
      containers:
      - name: myapp
        env:
        - name: APP_INITIAL_MEMORY_ALLOCATION
          value: "2097152"
        resources:
          requests:
            memory: "300"
            cpu: "100m"
          limits:
            memory: "300"
            cpu: "500m"
