apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: initmem

resources:
- namespace.yaml
- ../../base

patchesStrategicMerge:
- init-env.yaml
- ai.yaml
- db.yaml

secretGenerator:
- name: ai
  type: Opaque
  envs:
  - .env.ai
- name: db
  type: Opaque
  envs:
  - .env.db
