apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo
spec:
  template:
    spec:
      containers:
      - name: myapp
        env:
        - name: SPRING_DATASOURCE_HIKARI_MAX-LIFETIME
          value: "30000"
        - name: LOGGING_LEVEL_COM_ZAXXER_HIKARI
          value: "DEBUG"
